# Generated by Django 5.2.7 on 2025-11-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('Corporativo', 'Corporativo'), ('Residencial', 'Residencial'), ('Urbano', 'Urbano'), ('Interiorismo', 'Interiorismo')], max_length=50)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='proyectos/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
